### ISSUE TITLE
Get a solution

### ISSUE THREAD

**Issue by Maros112358** [jolibrain/wheatley#75]
Hello,

I trained a model on random 30x20 instances without uncertainty. I would like to use my trained model to solve my specific JSSP instances, but I can't find out how from the docs or the code itself. Is there any way to do this?
I would be happy for any answer. Thank you

**Comment by fantes** [comment]
Hi,

thank you for using wheatley! And sorry for the largely outdated documentation, rewriting has been on our todo list
for a long time ... 
In order to load your own jssp, you can use  --load_problem and you may also find the option --first_machine_id_is_one useful depending on your machine numbering  (we start at  0 , but taillard format starts at 1)
Depending on the size of your problem, it may be necessary to learn on subproblems using  --sample_n_jobs and try the learned agent on the global problem using --validate_on_total_data 
Finally, the main call has changed 2 or 3 days ago;  and now you need to do python -m jssp.train  instead of python ./train.py  .

I hope this helps, your questions are very welcome

**Comment by fantes** [comment]
Hi again, 
I've been told that I misunderstood your question. 

The code for pure solving/inference on a problem given an already learnt model is ... on our todo list.
But it is basically a subpart  of what is done during validation/eval phases, which is already extracted as jssp/eval.py. We should be able to add a solve.py very soon.

**Comment by Maros112358** [comment]
Hello @fantes, thank you for your quick response.
I think you understood my question correctly. I tried to extract the code for pure solving/inference from `eval.py` myself, but I failed, so I decided to ask. I will try to use your suggestions from your first answer and will come back with feedback.
If I eventually succeed with extracting the code, I will make a PR.

**Comment by fantes** [comment]
Hi @Maros112358 
@pierrot-lc has added a solve script , see a description at https://github.com/jolibrain/wheatley/pull/76 . Hope this helps.

**Comment by Maros112358** [comment]
Hello, I just checked the script. It's amazing and exactly what I needed. Thank you very much. 🚀 🎉
